#! /bin/sh

set -e

git config --global --get-all include.path | grep '~/.dotfiles/git/prefs.gitconfig' > /dev/null || \
git config --global --add include.path '~/.dotfiles/git/prefs.gitconfig'

git config --global --get-all includeIf.gitdir:~/Code/github.com/mdub/.path | grep '~/.dotfiles/git/prefs-mdub.gitconfig' > /dev/null || \
git config --global --add includeIf.'gitdir:~/Code/github.com/mdub/'.path '~/.dotfiles/git/prefs-mdub.gitconfig'

git config --global core.excludesfile '~/.gitignore'
touch ~/.gitignore
sort -u ~/.gitignore $(dirname $0)/.gitignore > /tmp/$$.gitignore && mv /tmp/$$.gitignore ~/.gitignore
