
brew "asdf"
brew "entr"
brew "exa"
brew "fd"
brew "fish"
brew "hub"
brew "ipcalc"
brew "joe"
brew "jq"
brew "most"
brew "ripgrep"

tap "homebrew/cask"
tap "homebrew/cask-fonts"

is_square = File.directory?("#{ENV["HOME"]}/Development/config_files")

cask "dash"
cask "docker"
cask "dropbox" unless is_square
cask "finicky"
cask "font-anonymous-pro"
cask "font-hack"
cask "font-source-code-pro"
cask "google-chrome" unless File.directory?("/Applications/Google Chrome.app")
cask "istat-menus"
cask "launchbar"
cask "rq"
cask "visual-studio-code"
cask "workflowy"
