set -u fish_color_autosuggestion 666666
set -u fish_color_cancel \x2dr
set -u fish_color_command 00BF32
set -u fish_color_comment 5C9900
set -u fish_color_cwd green
set -u fish_color_cwd_root red
set -u fish_color_end 8EEB00
set -u fish_color_error red
set -u fish_color_escape 00a6b2
set -u fish_color_normal normal
set -u fish_color_operator 00a6b2
set -u fish_color_param 04819E
set -u fish_color_quote 999900
set -u fish_color_redirection 00aaff
set -u fish_color_search_match bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -u fish_color_selection white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -u fish_color_status red
set -u fish_color_user brgreen
set -u fish_color_valid_path \x2d\x2dunderline
set -u fish_greeting
set -u fish_pager_color_completion normal
set -u fish_pager_color_description B3A06D\x1eyellow
set -u fish_pager_color_prefix white\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -u fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan
