#! /usr/bin/env fish

# Install fisher
type -q fisher; or curl -sL https://git.io/fisher | source

fisher install jorgebucaran/fisher
fisher install danhper/fish-ssh-agent
fisher install fishpkg/fish-git-util
fisher install jorgebucaran/replay.fish
fisher install oh-my-fish/plugin-aws
fisher install ~/.dotfiles/fish/fish-mdub
