#! /usr/bin/env fish

# Install fisher
type -q fisher; or curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
source ~/.config/fish/functions/fisher.fish

# Add my stuff
fisher add ~/.dotfiles/fish/fish-mdub
