#! /usr/bin/env fish

mkdir -p ~/.config/fish/conf.d

# Homebrew
set here (path dirname (status current-filename))
test -f ~/.config/fish/conf.d/00-homebrew.fish; or cp $here/00-homebrew.fish ~/.config/fish/conf.d/

# Install fisher
type -q fisher; or curl -sL https://git.io/fisher | source

fisher install jorgebucaran/fisher
fisher install danhper/fish-ssh-agent
fisher install jorgebucaran/replay.fish
# fisher install oh-my-fish/plugin-aws
fisher install ~/.dotfiles/fish/fish-mdub
